export const FETCH_ALL_NEWS = "FETCH_ALL_NEWS";
export const FETCH_ALL_NEWS_SUCCESS = "FETCH_ALL_NEWS_SUCCESS";
export const FETCH_ALL_NEWS_FAILURE = "FETCH_ALL_NEWS_FAILURE";
export const FETCH_NEWS = "FETCH_NEWS";
export const FETCH_NEWS_SUCCESS = "FETCH_NEWS_SUCCESS";
export const FETCH_NEWS_FAILURE = "FETCH_NEWS_FAILURE";
export const FETCH_NEWS_TOP = "FETCH_NEWS_TOP";
export const FETCH_NEWS_TOP_SUCCESS = "FETCH_NEWS_TOP_SUCCESS";
export const FETCH_NEWS_TOP_FAILURE = "FETCH_NEWS_TOP_FAILURE";

export const CREATE_BOOKMARK = "CREATE_BOOKMARK";
export const DELETE_BOOKMARK = "DELETE_BOOKMARK";
export const FETCH_BOOKMARK = "FETCH_BOOKMARK";
export const FETCH_BOOKMARK_DATA = "FETCH_BOOKMARK_DATA";

export const FETCH_TIMELINE = "FETCH_TIMELINE";
export const FETCH_TIMELINE_SUCCESS = "FETCH_TIMELINE_SUCCESS";
export const FETCH_TIMELINE_FAILURE = "FETCH_TIMELINE_FAILURE";
